### PR TITLE
Bugfix/long winded explanation typos

### PR DESCRIPTION
**Pull request by dszlachta**
Fixed a few typos and markdown syntax.

I couldn't build the docs and only used VS Code preview to make sure that the page renders correctly. `hugo` is throwing errors when trying to build.

### CODE REVIEW

**Comment by MattDodsonEnglish** [comment]
Oh thanks! I was actually just working on fixing those images you reported, and I noticed this formatting stuff too. You've saved me some work here.

I think this was coverted from a docx or something, so we got this formatting. I should have seen that before!

**Comment by MattDodsonEnglish** [comment]
Do you mind pasting the errors you got? Just for curiosity. I don't see anything wrong with your PR.

**Comment by dszlachta** [comment]
No worries, it was hard to spot, but I was reading this today and noticed some issues.
Here’s the output (Hugo version hugo v0.88.1+extended darwin/amd64 BuildDate=unknown):
```
ERROR 2021/09/06 17:29:54 render of "page" failed: execute of template failed: template: blog/single.html:3:5: executing "blog/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation
ERROR 2021/09/06 17:29:54 render of "page" failed: execute of template failed: template: blog/single.html:3:5: executing "blog/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation
ERROR 2021/09/06 17:29:54 render of "page" failed: execute of template failed: template: blog/single.html:3:5: executing "blog/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation
ERROR 2021/09/06 17:29:54 render of "page" failed: execute of template failed: template: blog/single.html:3:5: executing "blog/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation
Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:3:5: executing "_default/single.html" at <partial "head/head.html" .>: error calling partial: execute of template failed: template: partials/head/head.html:6:36: executing "head/stylesheet" at <partial "head/stylesheet.html" .>: error calling partial: "/Users/dawid/Upwork/trueblocks-docs/layouts/partials/head/stylesheet.html:7:45": execute of template failed: template: partials/head/stylesheet.html:7:45: executing "partials/head/stylesheet.html" at <toCSS $options>: error calling toCSS: no Resource provided in transformation
```

Dawid Szlachta

**Comment by MattDodsonEnglish** [comment]
Hmm, that partials file that it is calling has never changed, so I'm not sure what could be the matter. The best I can suggest is 
run `hugo mod clean` and try `hugo serve`.

 I've actually seen a similar `error calling toCSS` error before, but I don't remember where or how I fixed it :-(. Let me know if you can fix the issue, it'd be nice to have you be able to build the site yourself.

**Pull request merged**
